### ISSUE TITLE
simulation function

### ISSUE THREAD

**Issue by sommizzu** [git-final-team-project/prisoner-problem#4]
## Description
100 Prisoners Problem

## Tasks
- [ ] 시뮬레이션을 위한 상자와 숫자 초기화
- [ ] 죄수의 상자 선택 및 숫자 확인 루틴 구현
- [x] 시뮬레이션 실행 루틴 구현
- [ ] 'n'회 시행 후 결과 표시하기 위한 출력 형식 및 사용자 인터페이스

## Reference
- https://en.wikipedia.org/wiki/100_prisoners_problem
